[build]
base = "/"
publish = "/public/"
command = "npm run build"

[build.environment]
ZOLA_VERSION = "0.19.2"
VANMENXEL_BUILD = "prod"

[context.deploy-preview]
command = "zola build --base-url $DEPLOY_PRIME_URL"
