name = "vanmenxel-website-starter-kit"
pages_build_output_dir = "./public"

[vars]
ZOLA_VERSION = "0.19.2"

# Workaround, see: https://github.com/cloudflare/pages-build-image/issues/3#issuecomment-1646873666
UNSTABLE_PRE_BUILD = "asdf plugin add zola https://github.com/salasrod/asdf-zola && asdf install zola 0.19.2 && asdf global zola 0.19.2"
